### PR TITLE
Shortcode attempt

### PR DESCRIPTION
**Pull request by wereveal**
We talked at one point of using shortcodes. This would be my attempt at doing a shortcode for something simple like {{< span-colored blue >}}blue text{{< /span-colored >}} or something complex like {{< span-colored color="#A00" background="#0A0" >}}Red text with green background{{< /span-colored >}}.

I need to install a hugo instance somewhere so I could test this kind of thing. Any recommendations?

### CODE REVIEW

**Comment by Renddslow** [comment]
@wereveal I recommend just installing hugo locally. It runs as a CLI, so it's super easy to just run `hugo` and have it spit out the whole site.

What are you thinking the use-case of this would be tho?

**Comment by wereveal** [comment]
> @wereveal
> What are you thinking the use-case of this would be tho?

It is a common request I get when developing websites and one I use myself so it just comes up. It is a different way to put emphasis on a word or phrase compared to bold or italics. 

I would use it for example to highlight an inline scripture with a subtle color shift. 

Having thought about it I think a name change for the short code would be in order, something like words-colored, it's non-techies.

Maybe also to make it clearer to screen readers instead of span use em to indicate emphasis, but that would be contextual. Sometimes one just wants to have fun, for example, color gold, frankense, and myrrh gold, red, green, Christmas colors. We don't need to be so serious eh? 

Also, instead of using classes like text-primary as found in Bootstrap which is better practice, it is also harder for non-techies whereas words-colored blue is simple. 

Anyway, if you think it will be OK, maybe I should rename the file, change span to em and resubmit.

**Comment by Renddslow** [comment]
I'm good with that approach. We should probably, long-term, add either some logic or some static analysis to make sure any color they add meets WCAG AA contrast compliance.

**Comment by wereveal** [comment]
well, I guess I may have messed this pull request up, got two different merges mixed together. Updated the shortcode to as discussed and then also pushed the week's blog posts.

**Review by Renddslow — APPROVED** [review]

**Pull request merged**
